#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BOARD_NAME = "tropic01-universal-secure-device"
PINMUX_LEDGER_JSON = ROOT / "pcb" / BOARD_NAME / "production" / "pinmux-ledger.json"


def stm32_assignment(
    *,
    pin_name: str,
    physical_pin: int,
    function: str,
    bus: str,
    source_table: str,
    evidence: str,
    alternate_function: str | None = None,
) -> dict[str, object]:
    assignment: dict[str, object] = {
        "pin_name": pin_name,
        "physical_pin": physical_pin,
        "function": function,
        "bus": bus,
        "source": "STM32U585xx datasheet DS13086 Rev 10",
        "source_table": source_table,
        "evidence": evidence,
        "review_status": "source_backed",
    }
    if alternate_function is not None:
        assignment["alternate_function"] = alternate_function
    return assignment


def build_pinmux_ledger() -> dict[str, object]:
    return {
        "board": BOARD_NAME,
        "schema_version": 1,
        "status": "partial_datasheet_pinmux_confirmed",
        "sources": {
            "tropic01": {
                "title": "TROPIC01 datasheet ODD_TR01_datasheet_vA_11",
                "url": "https://github.com/tropicsquare/tropic01/blob/main/doc/datasheet/ODD_TR01_datasheet_vA_11.pdf",
                "evidence": "Table 1 TROPIC01 pinout and L1 Layer SPI description",
            },
            "display": {
                "title": "Newhaven NHD-2.4-240320AF-CSXP-CTP datasheet",
                "url": "https://newhavendisplay.com/content/specs/NHD-2.4-240320AF-CSXP-CTP.pdf",
                "evidence": "Pin Description and Interface Selection sections",
            },
            "stm32u5": {
                "title": "STM32U585xx datasheet DS13086 Rev 10",
                "url": "https://www.st.com/resource/en/datasheet/stm32u585ai.pdf",
                "evidence": "Figure 15 LQFP100 pinout, Table 27 pin definitions, Table 28/29 alternate functions",
            },
            "st25r3916b": {
                "title": "ST25R3916B/ST25R3917B/ST25R3919B datasheet DS13541 Rev 11",
                "url": "https://www.st.com/resource/en/datasheet/st25r3916b.pdf",
                "evidence": "Table 2 QFN32 pin assignment and Table 11 4-wire SPI signal lines",
            },
            "st25_antenna": {
                "title": "AN5276 antenna design for ST25R3916B-class devices",
                "url": "https://www.st.com/resource/en/application_note/an5276-antenna-design-for-st25r391616b-st25r391717b-st25r3918-and-st25r392020b-devices-stmicroelectronics.pdf",
                "evidence": "Antenna and matching design remain measurement-gated for final mechanics.",
            },
            "optiga": {
                "title": "OPTIGA Trust M datasheet Rev 3.70",
                "url": "https://www.infineon.com/assets/row/public/documents/30/49/infineon-optiga-trust-m-sls32aia-datasheet-en.pdf",
                "evidence": "Table 6 contact definitions for PG-USON-10 packages",
            },
            "usb4105": {
                "title": "GCT USB4105 product specification and drawing",
                "url": "https://gct.co/connector/usb4105",
                "evidence": "USB Type-C USB 2.0 receptacle, drawing-referenced footprint, current ratings for VBUS/GND",
            },
        },
        "tropic01": {
            "status": "datasheet_pinout_confirmed",
            "pins": {
                "1": "VCC",
                "2": "GND",
                "4": "GPO",
                "5": "SPI_SDI",
                "6": "SPI_SDO",
                "7": "SPI_SCK",
                "8": "SPI_CSN",
                "11": "VCC",
                "12": "GND",
                "23": "GND",
                "24": "VCC",
            },
            "nu_policy": "NU pins must follow the datasheet section 11 connection guidance before routing.",
            "spi_mode": "CPOL=0 CPHA=0 MSB-first",
            "host_policy": "TROPIC01 does not initiate communication; host MCU must wait for readiness or use GPO when configured.",
        },
        "display": {
            "status": "connector_pinout_confirmed_mcu_pinmux_pending",
            "module": "NHD-2.4-240320AF-CSXP-CTP",
            "tft_connector": "Molex 54132-4062",
            "touch_connector": "Molex 52271-0679",
            "driver_ics": ["ST7789VI", "FT5426-003"],
            "tft_4wire_spi_mode_select": {"IM0": "0", "IM1": "1", "IM2": "1"},
            "tft_spi_signals": {
                "SDA": "serial data input",
                "SCL_WRX": "serial clock in 3/4-wire SPI",
                "DCX": "data/command in 4-wire SPI",
                "CSX": "active-low chip select",
                "RESX": "active-low reset",
                "SDO": "serial data output",
            },
            "touch_i2c_signals": ["SCL", "SDA", "/INT", "/RESET"],
            "touch_i2c_pullups": "4.7k",
            "backlight": "LED-A anode 3.0 V / 160 mA max class; LED-K1..K4 cathodes to current driver return",
        },
        "stm32u5": {
            "status": "partial_lqfp100_pinmux_confirmed",
            "part": "STM32U585VIT6",
            "package": "LQFP100",
            "assignments": {
                "USB_VBUS_SENSE": stm32_assignment(
                    pin_name="PA9",
                    physical_pin=68,
                    function="OTG_FS_VBUS",
                    bus="usb2_device",
                    source_table="Figure 15 LQFP100 pinout and Table 27 pin definitions",
                    evidence="PA9 is LQFP100 pin 68 and lists OTG_FS_VBUS as additional function.",
                ),
                "USB_DM": stm32_assignment(
                    pin_name="PA11",
                    physical_pin=70,
                    function="OTG_FS_DM",
                    bus="usb2_device",
                    source_table="Figure 15 LQFP100 pinout and Table 27 pin definitions",
                    evidence="PA11 is LQFP100 pin 70 and lists OTG_FS_DM as additional function.",
                ),
                "USB_DP": stm32_assignment(
                    pin_name="PA12",
                    physical_pin=71,
                    function="OTG_FS_DP",
                    bus="usb2_device",
                    source_table="Figure 15 LQFP100 pinout and Table 27 pin definitions",
                    evidence="PA12 is LQFP100 pin 71 and lists OTG_FS_DP as additional function.",
                ),
                "TROPIC_SPI_CSN": stm32_assignment(
                    pin_name="PA4",
                    physical_pin=29,
                    function="SPI1_NSS",
                    alternate_function="AF5",
                    bus="tropic01_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PA4 is LQFP100 pin 29 and supports SPI1_NSS.",
                ),
                "TROPIC_SPI_SCK": stm32_assignment(
                    pin_name="PA5",
                    physical_pin=30,
                    function="SPI1_SCK",
                    alternate_function="AF5",
                    bus="tropic01_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PA5 is LQFP100 pin 30 and supports SPI1_SCK.",
                ),
                "TROPIC_SPI_MISO": stm32_assignment(
                    pin_name="PA6",
                    physical_pin=31,
                    function="SPI1_MISO",
                    alternate_function="AF5",
                    bus="tropic01_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PA6 is LQFP100 pin 31 and supports SPI1_MISO.",
                ),
                "TROPIC_SPI_MOSI": stm32_assignment(
                    pin_name="PA7",
                    physical_pin=32,
                    function="SPI1_MOSI",
                    alternate_function="AF5",
                    bus="tropic01_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PA7 is LQFP100 pin 32 and supports SPI1_MOSI.",
                ),
                "TROPIC_PWR_EN": stm32_assignment(
                    pin_name="PB0",
                    physical_pin=35,
                    function="GPIO output",
                    bus="tropic01_spi",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PB0 is an available LQFP100 GPIO near the lower edge pin bank.",
                ),
                "TROPIC_GPO": stm32_assignment(
                    pin_name="PB2",
                    physical_pin=37,
                    function="GPIO input / EXTI",
                    bus="tropic01_spi",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PB2 is an available LQFP100 GPIO for non-critical TROPIC01 GPO visibility.",
                ),
                "TFT_SPI_SCK": stm32_assignment(
                    pin_name="PC10",
                    physical_pin=78,
                    function="SPI3_SCK",
                    alternate_function="AF6",
                    bus="display_tft_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PC10 is LQFP100 pin 78 and supports SPI3_SCK.",
                ),
                "TFT_SPI_MOSI": stm32_assignment(
                    pin_name="PC12",
                    physical_pin=80,
                    function="SPI3_MOSI",
                    alternate_function="AF6",
                    bus="display_tft_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PC12 is LQFP100 pin 80 and supports SPI3_MOSI.",
                ),
                "TFT_CS": stm32_assignment(
                    pin_name="PC7",
                    physical_pin=64,
                    function="GPIO output",
                    bus="display_tft_spi",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PC7 is an available LQFP100 GPIO for display chip-select.",
                ),
                "TFT_DC": stm32_assignment(
                    pin_name="PC8",
                    physical_pin=65,
                    function="GPIO output",
                    bus="display_tft_spi",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PC8 is an available LQFP100 GPIO for 4-wire SPI D/C.",
                ),
                "TFT_RST": stm32_assignment(
                    pin_name="PC6",
                    physical_pin=63,
                    function="GPIO output",
                    bus="display_tft_spi",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PC6 is an available LQFP100 GPIO for display reset.",
                ),
                "TFT_BACKLIGHT_PWM": stm32_assignment(
                    pin_name="PA8",
                    physical_pin=67,
                    function="TIM1_CH1 / PWM",
                    alternate_function="AF1",
                    bus="display_tft_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 27 pin definitions",
                    evidence="PA8 is LQFP100 pin 67 and lists TIM1_CH1, suitable for backlight PWM.",
                ),
                "TFT_PWR_EN": stm32_assignment(
                    pin_name="PC9",
                    physical_pin=66,
                    function="GPIO output",
                    bus="display_tft_spi",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PC9 is an available LQFP100 GPIO for display rail control.",
                ),
                "TOUCH_I2C_SCL": stm32_assignment(
                    pin_name="PB8",
                    physical_pin=95,
                    function="I2C1_SCL",
                    alternate_function="AF4",
                    bus="display_touch_i2c",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PB8 is LQFP100 pin 95 and supports I2C1_SCL.",
                ),
                "TOUCH_I2C_SDA": stm32_assignment(
                    pin_name="PB9",
                    physical_pin=96,
                    function="I2C1_SDA",
                    alternate_function="AF4",
                    bus="display_touch_i2c",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PB9 is LQFP100 pin 96 and supports I2C1_SDA.",
                ),
                "TOUCH_INT": stm32_assignment(
                    pin_name="PE1",
                    physical_pin=98,
                    function="GPIO input / EXTI",
                    bus="display_touch_i2c",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PE1 is an available LQFP100 GPIO for touch interrupt.",
                ),
                "TOUCH_RST": stm32_assignment(
                    pin_name="PE0",
                    physical_pin=97,
                    function="GPIO output",
                    bus="display_touch_i2c",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PE0 is an available LQFP100 GPIO for touch reset.",
                ),
                "SE2_I2C_SCL": stm32_assignment(
                    pin_name="PB6",
                    physical_pin=92,
                    function="I2C4_SCL",
                    alternate_function="AF5",
                    bus="second_secure_element_i2c",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PB6 is LQFP100 pin 92 and supports I2C4_SCL, keeping OPTIGA separate from touch I2C.",
                ),
                "SE2_I2C_SDA": stm32_assignment(
                    pin_name="PB7",
                    physical_pin=93,
                    function="I2C4_SDA",
                    alternate_function="AF5",
                    bus="second_secure_element_i2c",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PB7 is LQFP100 pin 93 and supports I2C4_SDA, keeping OPTIGA separate from touch I2C.",
                ),
                "SE2_RST": stm32_assignment(
                    pin_name="PB5",
                    physical_pin=91,
                    function="GPIO output",
                    bus="second_secure_element_i2c",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PB5 is an available LQFP100 GPIO for OPTIGA active-low reset control.",
                ),
                "NFC_SPI_CSN": stm32_assignment(
                    pin_name="PB12",
                    physical_pin=51,
                    function="SPI2_NSS",
                    alternate_function="AF5",
                    bus="nfc_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PB12 is LQFP100 pin 51 and supports SPI2_NSS.",
                ),
                "NFC_SPI_SCK": stm32_assignment(
                    pin_name="PB13",
                    physical_pin=52,
                    function="SPI2_SCK",
                    alternate_function="AF5",
                    bus="nfc_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PB13 is LQFP100 pin 52 and supports SPI2_SCK.",
                ),
                "NFC_SPI_MISO": stm32_assignment(
                    pin_name="PB14",
                    physical_pin=53,
                    function="SPI2_MISO",
                    alternate_function="AF5",
                    bus="nfc_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PB14 is LQFP100 pin 53 and supports SPI2_MISO.",
                ),
                "NFC_SPI_MOSI": stm32_assignment(
                    pin_name="PB15",
                    physical_pin=54,
                    function="SPI2_MOSI",
                    alternate_function="AF5",
                    bus="nfc_spi",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PB15 is LQFP100 pin 54 and supports SPI2_MOSI.",
                ),
                "NFC_IRQ": stm32_assignment(
                    pin_name="PD0",
                    physical_pin=81,
                    function="GPIO input / EXTI",
                    bus="nfc_spi",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PD0 is an available LQFP100 GPIO for ST25R3916B IRQ.",
                ),
                "NFC_PWR_EN": stm32_assignment(
                    pin_name="PB1",
                    physical_pin=36,
                    function="GPIO output",
                    bus="nfc_spi",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PB1 is an available LQFP100 GPIO for NFC power-gate enable.",
                ),
                "QSPI_CLK": stm32_assignment(
                    pin_name="PE10",
                    physical_pin=41,
                    function="OCTOSPIM_P1_CLK",
                    alternate_function="AF10",
                    bus="qspi_nor",
                    source_table="Figure 15 LQFP100 pinout and Table 29 alternate function AF8 to AF15",
                    evidence="PE10 is LQFP100 pin 41 and supports OCTOSPIM_P1_CLK.",
                ),
                "QSPI_NCS": stm32_assignment(
                    pin_name="PE11",
                    physical_pin=42,
                    function="OCTOSPIM_P1_NCS",
                    alternate_function="AF10",
                    bus="qspi_nor",
                    source_table="Figure 15 LQFP100 pinout and Table 29 alternate function AF8 to AF15",
                    evidence="PE11 is LQFP100 pin 42 and supports OCTOSPIM_P1_NCS.",
                ),
                "QSPI_IO0": stm32_assignment(
                    pin_name="PE12",
                    physical_pin=43,
                    function="OCTOSPIM_P1_IO0",
                    alternate_function="AF10",
                    bus="qspi_nor",
                    source_table="Figure 15 LQFP100 pinout and Table 29 alternate function AF8 to AF15",
                    evidence="PE12 is LQFP100 pin 43 and supports OCTOSPIM_P1_IO0.",
                ),
                "QSPI_IO1": stm32_assignment(
                    pin_name="PE13",
                    physical_pin=44,
                    function="OCTOSPIM_P1_IO1",
                    alternate_function="AF10",
                    bus="qspi_nor",
                    source_table="Figure 15 LQFP100 pinout and Table 29 alternate function AF8 to AF15",
                    evidence="PE13 is LQFP100 pin 44 and supports OCTOSPIM_P1_IO1.",
                ),
                "QSPI_IO2": stm32_assignment(
                    pin_name="PE14",
                    physical_pin=45,
                    function="OCTOSPIM_P1_IO2",
                    alternate_function="AF10",
                    bus="qspi_nor",
                    source_table="Figure 15 LQFP100 pinout and Table 29 alternate function AF8 to AF15",
                    evidence="PE14 is LQFP100 pin 45 and supports OCTOSPIM_P1_IO2.",
                ),
                "QSPI_IO3": stm32_assignment(
                    pin_name="PE15",
                    physical_pin=46,
                    function="OCTOSPIM_P1_IO3",
                    alternate_function="AF10",
                    bus="qspi_nor",
                    source_table="Figure 15 LQFP100 pinout and Table 29 alternate function AF8 to AF15",
                    evidence="PE15 is LQFP100 pin 46 and supports OCTOSPIM_P1_IO3.",
                ),
                "BTN_LEFT": stm32_assignment(
                    pin_name="PE2",
                    physical_pin=1,
                    function="GPIO input / EXTI",
                    bus="side_buttons",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PE2 is LQFP100 pin 1 and available for side button input.",
                ),
                "BTN_RIGHT": stm32_assignment(
                    pin_name="PE3",
                    physical_pin=2,
                    function="GPIO input / EXTI",
                    bus="side_buttons",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PE3 is LQFP100 pin 2 and available for side button input.",
                ),
                "EXP_UART_TX": stm32_assignment(
                    pin_name="PD5",
                    physical_pin=86,
                    function="USART2_TX",
                    alternate_function="AF7",
                    bus="expansion",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PD5 is LQFP100 pin 86 and supports USART2_TX.",
                ),
                "EXP_UART_RX": stm32_assignment(
                    pin_name="PD6",
                    physical_pin=87,
                    function="USART2_RX",
                    alternate_function="AF7",
                    bus="expansion",
                    source_table="Figure 15 LQFP100 pinout and Table 28 alternate function AF0 to AF7",
                    evidence="PD6 is LQFP100 pin 87 and supports USART2_RX.",
                ),
                "SWDIO": stm32_assignment(
                    pin_name="PA13",
                    physical_pin=72,
                    function="JTMS/SWDIO",
                    bus="manufacturing_test",
                    source_table="Figure 15 LQFP100 pinout and Table 27 pin definitions",
                    evidence="PA13 is LQFP100 pin 72 and carries the SWDIO debug function.",
                ),
                "SWCLK": stm32_assignment(
                    pin_name="PA14",
                    physical_pin=76,
                    function="JTCK/SWCLK",
                    bus="manufacturing_test",
                    source_table="Figure 15 LQFP100 pinout and Table 27 pin definitions",
                    evidence="PA14 is LQFP100 pin 76 and carries the SWCLK debug function.",
                ),
                "BOOT0": stm32_assignment(
                    pin_name="PH3-BOOT0",
                    physical_pin=94,
                    function="BOOT0 strap",
                    bus="manufacturing_test",
                    source_table="Figure 15 LQFP100 pinout",
                    evidence="PH3-BOOT0 is LQFP100 pin 94.",
                ),
                "NRST": {
                    "pin_name": "NRST",
                    "physical_pin": 14,
                    "function": "Reset",
                    "bus": "manufacturing_test",
                    "source": "STM32U585xx datasheet DS13086 Rev 10",
                    "source_table": "Figure 15 LQFP100 pinout",
                    "evidence": "NRST is LQFP100 pin 14.",
                    "review_status": "source_backed",
                },
            },
            "constraint": "This is a source-backed Rev A0 pinmux intent, not a routed-board release. ERC, DRC, impedance review, NFC matching, and schematic net binding remain release gates.",
        },
        "st25r3916b": {
            "status": "controller_pinout_confirmed_antenna_matching_required",
            "part": "ST25R3916B-AQET",
            "qfn32_pins": {
                "20": "I2C_EN",
                "27": "IRQ",
                "29": "BSS",
                "30": "SCLK",
                "31": "MOSI",
                "32": "MISO",
            },
            "spi_mode": "CPOL=0 CPHA=1 MSB-first; pull I2C_EN to GND for SPI operation.",
            "antenna_constraint": "RFO1/RFO2/RFI1/RFI2 matching values are not frozen; tune with final antenna FPC/PCB and enclosure.",
        },
        "optiga": {
            "status": "datasheet_pinout_confirmed",
            "part": "OPTIGA-TRUST-M-SLS32AIA",
            "package": "PG-USON-10-2/-4 class",
            "pins": {
                "1": "GND",
                "3": "SDA",
                "8": "SCL",
                "9": "RST",
                "10": "VCC",
            },
            "i2c_policy": "Use a dedicated STM32 I2C bus for OPTIGA rather than sharing with the touch controller.",
        },
        "usb4105": {
            "status": "datasheet_and_drawing_confirmed",
            "part": "USB4105-GF-A",
            "type": "USB Type-C receptacle for USB 2.0, SMT top mount",
            "connector_policy": "Use as a sink/device receptacle with CC1/CC2 Rd pull-downs, ESD protection, and drawing-verified footprint.",
        },
        "release_gates": [
            "no_llm_invented_pin_numbers",
            "stm32_cube_or_datasheet_pinmux_review",
            "st25r3916b_pin_and_matching_review",
            "kicad_schematic_nets_match_this_ledger",
            "erc_clean_before_pcb_update",
        ],
    }


def write_pinmux_ledger(path: Path = PINMUX_LEDGER_JSON) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(build_pinmux_ledger(), indent=2, sort_keys=True) + "\n", encoding="utf-8")


def main() -> int:
    write_pinmux_ledger()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
